/**
 * This file is generated by 'file2variable-cli'
 * It is not mean to be edited by hand
 */
// tslint:disable
import { Others } from "./index";

// @ts-ignore
export function othersTemplateHtml(this: Others) {var _vm=this;var _h=_vm.$createElement;var _c=_vm._self._c||_h;return _c('div',{staticClass:"panel"},[_c('button',{staticClass:"btn btn-primary",on:{"click":function($event){_vm.resaveFailedLogs()}}},[_vm._v("resave failed logs")])])}
// @ts-ignore
export var othersTemplateHtmlStatic = [  ]
// tslint:enable
