import "vue";
import "vue-class-component";
import { __decorate, __extends } from "tslib";
export { __decorate, __extends };
import "reconnection/browser";
import * as moment from "moment";
(global as any).moment = moment;
import "chart.js";
import "protobufjs";
import "ajv";
import "rpc-on-ws";
