import "vue";
import "vue-class-component";
import { __decorate, __extends } from "tslib";
(global as any).__decorate = __decorate;
(global as any).__extends = __extends;
import "reconnection/browser/browser";
import * as moment from "moment";
(global as any).moment = moment;
import "chart.js";
import "protobufjs";
import "ajv";
import "rpc-on-ws/browser";
import "relative-time-component/vue";
import "tab-container-component/vue";
import "rxjs/Subject";
